AllCops:
  Exclude:
    - 'bin/*'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'config/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'

Style/MixinUsage:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

ConstantDefinitionInBlock:
  Enabled: false

HashLikeCase:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false
