AllCops:
  Exclude:
    - 'bin/*'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'config/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false
